### ISSUE TITLE
uh oh, you got me curious :P

### ISSUE THREAD

**Issue by ghost** [akuttruff/homepage#1]
This looks super clean.  It already up somewhere?

**Comment by ghost** [comment]
p.s. I do believe the symmetry in our github usernames is choice

**Comment by ghost** [comment]
Ohhhh, shit, is it this one?
http://amiekuttruff.com/

even the html output is beautiful.  
you and other misc functional lispy whispers are nudging me toward swapping out sinatra for clojure/cljs

This code is about as simple and declarative as it could get.

**Comment by akuttruff** [comment]
Haha thanks dude! I missed this ^^ was not expecting anyone to file any issues :)

**Comment by ghost** [comment]
Lol I put in a feature request for a "kudos" mechanism that is more interactive than "starring" a repo.  They responded warmly

Sadly no other way than filing an "issue" to engage with repo maintainers.

cc/ @GithubDecisionMakers :)
